<style>
p.newsspec_9779__not-supported {
	background: black;
	color: white;
	padding: 0.5em;
}
p.newsspec_9779__not-supported img {
	display: block;
	margin-bottom: 1em;
	width: 100%;
}
</style>
<p class="newsspec_9779__not-supported"><img src="http://newsimg.bbc.co.uk/media/images/79733000/jpg/_79733432_code624.jpg" />This interactive video is a new technology being trialled by the BBC Connected Studio innovation programme and is best viewed with the latest version of Flash.  It does not currently work on iOS or Android mobile devices or tablets. You can find a non-interactive version of the content below.</p>